<a href="https://colab.research.google.com/github/saurabh18102001/Python-Library/blob/main/numpyNote.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Notes**

---







In [2]:
import numpy as np



# **Creating Numpy**

---



In [ ]:
x = np.array([1,2,3,4])
print(x)        #[1 2 3 4]
print(type(x))  #<class 'numpy.ndarray'>
print(x.ndim)   #1

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [ ]:
y = [1,2,3,4]
print(y)        #[1, 2, 3, 4]
print(type(y))  #<class 'list'>

[1, 2, 3, 4]
<class 'list'>


In [ ]:
#User input array creating
# range() function humesha (0 to n-1) chalta hai

lists = []
for i in range(1,5):
  your_input = int(input("Enter the Number: "))    #input() function always give string return type.
  lists.append(your_input)
print(np.array(lists))


Enter the Number: 1
Enter the Number: 1
Enter the Number: 1
Enter the Number: 1
[1 1 1 1]


# **ndim  and  ndmin**

---


1.  ndim => used to identify the dimension of an array
2.  ndmin => used to create n dimension of an array




In [ ]:
x = np.array([1,2],ndmin = 10)
# print(x.ndim)     10
# print(x)      [[[[[[[[[[1 2]]]]]]]]]]


10


# **arange([start,] stop[, step,][, dtype])**


---



1.   It start with 0.
2.   Or khatam en number pahla hoga jaise ki (1,4) hain start 1 sa or end 3 pa hoga.
3.  Ya array banana main kaam aata hai shortcut jaise bol sakta hai.






In [ ]:
# numpy.arange method
#Syntax :  arange([start,] stop[, step,][, dtype])

print("A", np.arange(4).reshape(2, 2), "\n")  #A [[0 1]
                                              #   [2 3]]
print("A", np.arange(4, 10), "\n")  #A [4 5 6 7 8 9]
print("A", np.arange(4, 20, 3), "\n") #A [ 4  7 10 13 16 19]

A [[0 1]
 [2 3]] 

A [4 5 6 7 8 9] 

A [ 4  7 10 13 16 19] 



# **numpy.reshape(array, shape, order = 'C')**

---

Array which is reshaped without changing the data.


In [ ]:
# numpy.reshape() method


# array = geek.arrange(8)
# The 'numpy' module has no attribute 'arrange'
array1 = np.arange(8)
print("Original array : \n", array1)

# shape array with 2 rows and 4 columns
array2 = np.arange(8).reshape(2, 4)
print("\narray reshaped with 2 rows and 4 columns : \n",
      array2)

# shape array with 4 rows and 2 columns
array3 = np.arange(8).reshape(4, 2)
print("\narray reshaped with 4 rows and 2 columns : \n",
      array3)

# Constructs 3D array
array4 = np.arange(8).reshape(2, 2, 2)
print("\nOriginal array reshaped to 3D : \n",
      array4)

Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

array reshaped with 4 rows and 2 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
x = np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


# **Create NumPy array using NumPy functions**

---



In [8]:
#Zeroes array

x = np.zeros(5)
print(x)
y = np.zeros((2,3))
print(y)
z = np.zeros((2,3,4))
print(z)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [6]:
#Ones array

x = np.ones(5)
print(x , "\n")
y = np.ones((2,3))
print(y, "\n")
z = np.ones((2,3,4))
print(z, "\n")

[1. 1. 1. 1. 1.] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]] 



In [9]:
#Empty array
x = np.empty(5)
print(x)
y = np.empty((2,3))
print(y)
z = np.empty((2,3,4))
print(z)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [10]:
#Range array

x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
#Diagonal array

x = np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
#Linspace array

x = np.linspace(0,10,num = 5)     #from 0 to 10 there will be 5 number only.
print(x)

[ 0.   2.5  5.   7.5 10. ]


# **Create NumPy array with Random Numbers**

---



In [19]:
# rand() function

x = np.random.rand(5)
print(x)
y = np.random.rand(2,2)
print(y)
z = np.random.rand(2,2,3)
print(z)

[0.9734106  0.71117346 0.65555032 0.43704595 0.68257709]
[[0.98344775 0.72156807]
 [0.90286059 0.68535085]]
[[[0.34368249 0.60872429 0.37490204]
  [0.00808263 0.03496386 0.04149028]]

 [[0.89942911 0.78969862 0.94199502]
  [0.97243409 0.18957561 0.26926637]]]


In [20]:
# randn() function

x = np.random.randn(5)
print(x)
y = np.random.randn(2,2)
print(y)
z = np.random.randn(2,2,3)
print(z)

[-0.52685526  0.19956103  0.22567204 -0.76903015 -0.83317263]
[[ 0.1646395   1.43055313]
 [ 0.31286383 -1.07723912]]
[[[-0.55727134  0.38279162  0.69859494]
  [-1.66172016 -1.6462394   0.41857671]]

 [[ 1.36449638  0.07571052  0.14994407]
  [-0.37137442 -0.52025197  0.14119154]]]


In [24]:
# ranf() function

x = np.random.ranf(5)
print(x)
y = np.random.ranf((2,2))
print(y)
z = np.random.ranf((2,2,3))
print(z)

[0.49981146 0.14156416 0.28903716 0.12967046 0.59016481]
[[0.54656459 0.28312672]
 [0.61789074 0.81633557]]
[[[0.25632633 0.93875421 0.14867587]
  [0.98120437 0.94675149 0.83636034]]

 [[0.44663113 0.62634859 0.29358448]
  [0.11029195 0.03547342 0.18523401]]]


In [39]:
# randint(min , max , total_value) function


y = np.random.randint(10,20,5)
print(y)


[19 14 15 16 15]


# **Data Type**

---



In [40]:
a = np.array([1,2,3])
print(a.dtype)

int64


# **Shape**

Shape is used to find out the dimension of the array in row and column

---




In [43]:
a = np.array([[[1,2,3],[4,5,6]]])
print(a.shape)

(1, 2, 3)


# **Reshape**

Reshape convert the array into n dimension *array*

-1 is used to convert the array into one dimension array

---



In [47]:
a = np.array([1,2,3,4,5,6])
print(a.reshape(-1))

[1 2 3 4 5 6]


# **Arithmetic Operators**

---



In [51]:
#ONE DIMENSION ARRAY

a = np.array([1,2,3,4,5])
print(a+3)
print(a-3)
print(a*3)
print(a/3)
print(a//3)
print(a%3)


[4 5 6 7 8]
[-2 -1  0  1  2]
[ 3  6  9 12 15]
[0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0 0 1 1 1]
[1 2 0 1 2]


In [53]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[0 0 0 0 0]
[1 2 3 4 5]
[      1     128    6561  262144 9765625]


In [56]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(np.reciprocal(a))
print(np.power(a,b))

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[1 2 3 4 5]
[1 0 0 0 0]
[      1     128    6561  262144 9765625]


In [57]:
# TWO DIMENSION ARRAY

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[6,7,8],[9,10,11]])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(np.reciprocal(a))
print(np.power(a,b))

[[ 7  9 11]
 [13 15 17]]
[[-5 -5 -5]
 [-5 -5 -5]]
[[ 6 14 24]
 [36 50 66]]
[[0.16666667 0.28571429 0.375     ]
 [0.44444444 0.5        0.54545455]]
[[1 2 3]
 [4 5 6]]
[[1 0 0]
 [0 0 0]]
[[        1       128      6561]
 [   262144   9765625 362797056]]


# **Arithmetic Functions**

In [58]:
a = np.array([1,2,3,4,5])
print(np.min(a))
print(np.max(a))
print(np.argmin(a))
print(np.argmax(a))
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))
print(np.cumsum(a))


1
5
0
4
[1.         1.41421356 1.73205081 2.         2.23606798]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1  3  6 10 15]


In [64]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[6,7,8],[9,10,11]])
print(np.min(a,axis = 1))
print(np.max(a,axis = 1))
print(np.argmin(a,axis = 1))
print(np.argmax(a,axis = 1))
print(np.cumsum(a,axis =1))


[1 4]
[3 6]
[0 0]
[2 2]
[[ 1  3  6]
 [ 4  9 15]]


In [6]:
#Shuffle
a = np.array([1,2,3,4,5])
np.random.shuffle(a)
print(a)

[5 1 3 4 2]


In [7]:
#unique
a = np.array([1,2,3,4,5,1,2,3,4,5])
print(np.unique(a))

[1 2 3 4 5]


In [9]:
#to get the index and the count
a = np.array([1,2,3,4,5,1,2,3,4,5,3,7])
print(np.unique(a,return_index = True,return_counts=True))

(array([1, 2, 3, 4, 5, 7]), array([ 0,  1,  2,  3,  4, 11]), array([2, 2, 3, 2, 2, 1]))


In [13]:
#resize -> single to n dimension array

a = np.array([1,2,3,4,5])
print(np.resize(a,(2,3)))
print()
print(np.resize(a,(3,2,2)))

[[1 2 3]
 [4 5 1]]

[[[1 2]
  [3 4]]

 [[5 1]
  [2 3]]

 [[4 5]
  [1 2]]]


In [16]:
# flatten and ravel -> used to convert 2d aaray into 1d array
a = np.array([[1,2,3],[4,5,6]])
print(a.flatten(order="F"))
print()
print(a.ravel(order="F"))

[1 4 2 5 3 6]

[1 4 2 5 3 6]


# **Indexing in NumPy**

In [65]:
a = [1,2,3,4,5]
print(a[3])

4


In [66]:
a = [[1,2,3],[4,5,6]]
print(a[1][2])

6


# **Slicing in NumPy**

In [73]:
a = np.array([1,2,3,4,5])
print("to end", a[2:])
print("from start", a[:4])
print("to middle", a[1:3])


to end [3 4 5]
from start [1 2 3 4]
to middle [2 3]


In [74]:
a = np.array([[1,2,3],[4,5,6]])
print(a[0,1:])

[2 3]


# **Iterating in NumPy**

In [75]:
a = np.array([1,2,3,4,5])
for i in a:
  print(i)

1
2
3
4
5


In [84]:
a = np.array([[1,2,3,4,5],[5,6,7,8,9]])
for i in a:
  # print(i)
  for j in i:
    print(j)
print(a)

1
2
3
4
5
5
6
7
8
9
[[1 2 3 4 5]
 [5 6 7 8 9]]


In [85]:
a = [[[1,2,3,4],[5,6,7,8],[9,10,11,12]]]
for i in a:
  for j in i:
    for k in j:
      print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [86]:
#nditer()
a = [[[1,2,3,4],[5,6,7,8],[9,10,11,12]]]
for i in np.nditer(a):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [87]:
#ndenumerate()
a = np.array([[1,2,3,4,5],[5,6,7,8,9]])
for i,j in np.ndenumerate(a):
  print(i,j)


(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9


# **JOIN Array**

In [88]:
#concatenate()
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(np.concatenate((a,b)))

[1 2 3 4 5 6 7 8]


In [96]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.concatenate((a,b),axis = 0))
print()
print(np.concatenate((a,b),axis = 1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [100]:
#stack()
# hstack() -> horizontak
# vstack() -> vertical
# dstack() ->height
#  if we use abobe function than axis is not required.
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(np.stack((a,b)))  #axis = 0
print()
print(np.stack((a,b),axis = 1))

[[1 2 3 4]
 [5 6 7 8]]

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


# **SPLIT Array**

In [102]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.array_split(a,3))
print()
print(np.array_split(a,4))

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [104]:
a = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
print(np.array_split(a,3))
print()
print(np.array_split(a,4))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


# **Search**

In [107]:
a = np.array([1,2,3,4,5,6,7,4,9])
print(np.where(a == 4))

(array([3, 7]),)


In [108]:
a = np.array([1,2,3,4,5,6,7,4,9])
print(np.where(a > 4))

(array([4, 5, 6, 8]),)


# **Search Sorted**

In this the array is shorted and it tells where the specific value should be inserted.

OR

The NumPy searchsorted() function can be used to find the index value where the new elements should be inserted in the sorted array, and the order of an array be preserved.

---



In [117]:
a = [1,2,3,4,6,7,8,9,10,11,13,14,15,16]
print(np.searchsorted(a,5,side = 'right'))
print()
print(np.searchsorted(a,5,side = 'left'))

4

4


In [119]:
a = [1,2,3,4,6,7,8,9,10,11,13,14,15,16]
print(np.searchsorted(a,[5,12],side = 'right'))
print()
print(np.searchsorted(a,[5,12],side = 'left'))

[ 4 10]

[ 4 10]


# **SORT ARRAY**

putting elements in an ordered sequence

---



In [120]:
a = np.array([1,38,58,45,93,83,25,10,28,93])
print(np.sort(a))

[ 1 10 25 28 38 45 58 83 93 93]


# **FILTER Array**

Getting some elements out of existing elements array and creating  a new  array out of them.

---



In [122]:
a = np.array([1,2,3,4,5,6,7,8,9])
f = [True,False,True,False,True,False,True,False,True]
print(a[f])

[1 3 5 7 9]


# **NumPy Array Functions(Insert and Delete Functions)**



In [23]:
#INSERT

a = np.array([1,2,3,4,5])
# print(np.insert(a,3,100))      #(array_name, index , value)
print(np.insert(a,(2,4),100))   #it never accepts the float value
print(np.append(a,6.5))


[  1   2 100   3   4 100   5]
[1.  2.  3.  4.  5.  6.5]


In [24]:
#DELETE

a = np.array([1,2,3,4,5])
print(np.delete(a,3))

[1 2 3 5]


# **Matrix in NumPy Array**

1.In addition operator there is no difference between array and matrix.

2.In substraction operator there is no difference between array and matrix.

3.But in multiply operator both are difference.

In [25]:
a = np.matrix([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [27]:
a = np.matrix([[1,2,3],[4,5,6]])
b = np.matrix([[7,8,9],[10,11,12]])
print(a+b)
print()
print(a-b)
print()
# print(a*b)      error is showing (shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0))


[[ 8 10 12]
 [14 16 18]]

[[-6 -6 -6]
 [-6 -6 -6]]



In [28]:
#Matrix multiplication is also known as Dot multiplication.
# Two ways to perform multiplication.
# 1. a*b
# 2. a.dot(b)
# 3. It follows the broadcast rule

a = np.matrix([[1,2,3],[4,5,6]])   #2*3
b = np.matrix([[7,8],[9,10],[11,12]])   #3*2
print(a*b)
print()
print(a.dot(b))


[[ 58  64]
 [139 154]]

[[ 58  64]
 [139 154]]


# **Matrix Function**

In [30]:
#Transpose

a = np.matrix([[1,2,3],[4,5,6]])
print(a.T)
print()
print(np.transpose(a))

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [32]:
#Swapaxes

a = np.matrix([[1,2,3],[4,5,6]])
print(a.swapaxes(0 ,1))
print()
print(np.swapaxes(a,0,1))

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [33]:
#Inverse

a = np.matrix([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [35]:
#Power
# power = 0 => Identity Matrix
# power > 0 => Multiplication
# power < 0 => inverse * power

a = np.matrix([[1,2],[3,4]])
print(np.linalg.matrix_power(a,2))     #(array, power)
print()
print(np.linalg.matrix_power(a,0))
print()
print(np.linalg.matrix_power(a,-2))

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [39]:
#Determinant

a = np.matrix([[1,2,4],[3,4,2],[1,5,3]])
print(np.linalg.det(a))

32.000000000000014
